### PR TITLE
Fallback when intl is missing

### PR DESCRIPTION
**Pull request by splitbrain**
This implements a mechanism to replace the locale aware part of the function with differrent formatter classes.

For now it simply implements a fallback to a non-locale aware formatting using DateTime->format() when the intl extension is missing. Future extension could implement making use of strftime() if it still exist or implement locale formatting in pure PHP.

For testing a environment variable STRFTIME_NO_INTL can be set to force using the fallback.

Currently the test for the gregorian calendar jump fails, but I don't understand the issue well enough to fix it.

### CODE REVIEW

**Comment by alphp** [comment]
I have created some tests to more rigorously check the localization formats.

At the moment only the following locations are checked:

- English (England) en-EN
- Spanish (Spain) en-ES
- Euskera eu
- Italian (Italy) it-IT
- Italian (Switzerland) it-CH

The IntlLocaleFormatter class passes all tests.
The DateLocaleFormatter class fails all tests.

**Review by alphp — CHANGES_REQUESTED** [review]
The DateLocaleFormatter class has to work the same as IntlDateFormatter for any locale.
It would be interesting to add the locations as Traits.

**Comment by splitbrain** [comment]
That's not what the intention of this formatter is. It is not meant to replace the IntlFormatter, it is meant as a last resort. Instead of the whole application fatally failing when intl isn't available, a user will see the proper date and time, but in English. So the goal would be that this class passes the tests for the `en` (or possibly `C`) locale only.

**Comment by bohwaz** [comment]
Interesting take, but splitting the code in multiple files/classes is missing what was intended here, to have a single file/function to drop in any legacy project (not everyone uses Composer, here I'm not using it because all third party code must be read and validated before being deployed in production) to replace strftime.

If you begin to split the code and use autoloading, that no longer works. Not saying that it's a bad idea, just that it restricts the original scope I wrote this code for :)

**Comment by alphp** [comment]
I have created a specific branch for this sub project: fallback-intl

**Review by alphp — APPROVED** [review]

**Pull request merged**
